var mongoose = require('mongoose');
var Schema = mongoose.Schema;

var passportLocalMongoose = require('passport-local-mongoose');

var User = new Schema({
    username: String,
    password: String,
    provider: String, // The provider with which the user authenticated (facebook, twitter, etc.).
    id: String, // A unique identifier for the user, as generated by the service provider.
    displayName: String, // The name of this user, suitable for display.
    name: Object,
        familyName: String, // The family name of this user, or "last name" in most Western languages.
        givenName: String, // The given name of this user, or "first name" in most Western languages.
        middleName: String, // The middle name of this user.
    emails: Array [{
        value: String, // The actual email address.
        type: String, // The type of email address (home, work, etc.).
    }],
    photos: Array [{
        value: String // The URL of the image.
    }]
});

User.plugin(passportLocalMongoose);
module.exports = mongoose.model('User', User);